[package]
name = "converge-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
ciborium.workspace = true
fastcdc.workspace = true
semver = "1.0.28"
serde.workspace = true
serde_bytes.workspace = true

[dev-dependencies]
tempfile.workspace = true
serde_json.workspace = true
