[package]
name = "converge-server"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
blake3.workspace = true
converge-model.workspace = true
diffy.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true

[dev-dependencies]
converge-client.workspace = true
reqwest.workspace = true
tempfile.workspace = true
